version: '3.7'            
services:
  
  db:                      
    image: mariadb:10.2    
    restart: always
    #environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ojs
      MYSQL_USER: ojs
      MYSQL_PASSWORD: ojs

  ojs:                    
    image: lucasdiedrich/ojs:latest   
    restart: always
    ports:
      - "8080:80" 
      - "8443:443"
    environment:
      SERVERNAME: 'myserver.mydomain'
      OJS_CLI_INSTALL: 1
      OJS_DB_HOST: 'db'
    depends_on: 
     - db
